In [1]:
import numpy as np
from inviter import get_eigenvector_by_inviter
from tqdm.notebook import tqdm
from inverse import inverse
import random

## 1. Lower triangular matrix

In [2]:
seed = 42
np.random.seed(seed)
random.seed(seed)

In [3]:
N = 5
L = np.random.uniform(-10, 10, size=(N, N))
L = np.tril(L)

print("Given matrix")
L.round(4)

Given matrix


array([[-2.5092,  0.    ,  0.    ,  0.    ,  0.    ],
       [-6.8801, -8.8383,  0.    ,  0.    ,  0.    ],
       [-9.5883,  9.3982,  6.6489,  0.    ,  0.    ],
       [-6.3319, -3.9152,  0.4951, -1.3611,  0.    ],
       [ 2.2371, -7.2101, -4.1571, -2.6728, -0.8786]])

In [4]:
eigenvalues = L.diagonal()
print("Eigenvalues:", eigenvalues)

Eigenvalues: [-2.50919762 -8.83832776  6.64885282 -1.36109963 -0.87860032]


Find eigenvectors

In [5]:
S = np.array([
    get_eigenvector_by_inviter(L, eigenvalue=l, eps=1e-15, noise_ratio=0.1)
    for l in eigenvalues
])

Restore original matrix from our decomposition

In [6]:
At = S.T @ np.diag(eigenvalues) @ inverse(S.T, eps=1e-15)
loss_matrix = At-L
print("Loss matrix")
print(loss_matrix.round(4))
print("2-Norm of loss:", np.linalg.norm(loss_matrix))

Loss matrix
[[ 0.  0.  0. -0. -0.]
 [ 0.  0.  0. -0.  0.]
 [ 0.  0.  0. -0. -0.]
 [ 0.  0.  0. -0.  0.]
 [ 0.  0.  0. -0.  0.]]
2-Norm of loss: 1.3443456034696013e-14


In [7]:
print("Found vectors * lambda")
np.array([eigenvalues[i] * S[i] for i in range(N)])

Found vectors * lambda


array([[ 8.75326650e-01, -9.51527801e-01,  1.89293008e+00,
         7.66368858e-01,  6.73769475e-01],
       [-7.29539540e-18, -5.83833542e+00,  3.54291902e+00,
        -3.29161945e+00, -4.54343959e+00],
       [ 1.68178546e-17, -1.82704927e-17, -5.75763897e+00,
        -3.55903725e-01,  3.30608073e+00],
       [-5.93789673e-28,  6.45481755e-28, -1.28409472e-27,
        -2.41803382e-01, -1.33944889e+00],
       [-5.64229208e-24,  6.13347798e-24, -1.22016886e-23,
         8.70963089e-19, -8.78600316e-01]])

In [8]:
print("Found vectors after applying L")
np.array([L @ S[i] for i in range(N)])

Found vectors after applying L


array([[ 8.75326650e-01, -9.51527801e-01,  1.89293008e+00,
         7.66368858e-01,  6.73769475e-01],
       [-2.07115976e-18, -5.83833542e+00,  3.54291902e+00,
        -3.29161945e+00, -4.54343959e+00],
       [-6.34685740e-18,  6.88418307e-18, -5.75763897e+00,
        -3.55903725e-01,  3.30608073e+00],
       [-1.09465583e-27,  1.18995058e-27, -2.36723849e-27,
        -2.41803382e-01, -1.33944889e+00],
       [-1.61138411e-23,  1.75166120e-23, -3.48468449e-23,
         1.34926182e-18, -8.78600316e-01]])

In [9]:
mean_loss = np.mean([
    np.linalg.norm(L @ S[i] - eigenvalues[i] * S[i]) 
    for i in range(N)
])
print("2-Norm of the loss:", mean_loss)
assert mean_loss < 1e-5, "TEST FAILED"
print("TEST PASSED")

2-Norm of the loss: 4.069584932039818e-16
TEST PASSED


## 2. Complex lower triangular matrix

In [10]:
N = 3
Ax = np.random.uniform(-10, 10, size=(N, N)).round(2).astype(complex)
Ay = np.random.uniform(-10, 10, size=(N, N)).round(2).astype(complex)
A = np.tril(Ax + 1j*Ay)

print("Given matrix")
A

Given matrix


array([[ 9.39-3.49j,  0.  +0.j  ,  0.  +0.j  ],
       [ 7.9 +6.57j,  1.96-2.86j,  0.  +0.j  ],
       [-8.23+0.85j, -6.08-7.18j, -9.1 +6.04j]])

In [11]:
eigenvalues = A.diagonal()
print("Eigenvalues:", eigenvalues)

Eigenvalues: [ 9.39-3.49j  1.96-2.86j -9.1 +6.04j]


Find eigenvectors

In [12]:
S = np.array([
    get_eigenvector_by_inviter(A, eigenvalue=l, max_iters=500, noise_ratio=0.1)
    for l in eigenvalues
])

Restore original matrix from our decomposition

In [13]:
At = S.T @ np.diag(eigenvalues) @ inverse(S.T, eps=1e-15)
loss_matrix = At-A
print("Loss matrix")
print(loss_matrix.round(4))
print("2-Norm of loss:", np.linalg.norm(loss_matrix))

Loss matrix
[[ 0.-0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -0.-0.j -0.+0.j]]
2-Norm of loss: 6.261178156878394e-15


In [14]:
print("Found vectors * lambda")
np.array([eigenvalues[i] * S[i] for i in range(N)])

Found vectors * lambda


array([[-0.37723154+5.45419462j, -5.64682336+4.98684085j,
         3.70218896+0.01608392j],
       [ 0.        +0.j        , -1.5257392 -2.45451927j,
        -1.60089456+1.05156628j],
       [-0.        +0.j        , -0.        +0.j        ,
         8.99385313+6.19695134j]])

In [15]:
print("Found vectors after applying A")
np.array([A @ S[i] for i in range(N)])

Found vectors after applying A


array([[-0.37723154+5.45419462j, -5.64682336+4.98684085j,
         3.70218896+0.01608392j],
       [ 0.        +0.j        , -1.5257392 -2.45451927j,
        -1.60089456+1.05156628j],
       [ 0.        +0.j        ,  0.        +0.j        ,
         8.99385313+6.19695134j]])

In [16]:
mean_loss = np.mean([
    np.linalg.norm(A @ S[i] - eigenvalues[i] * S[i]) 
    for i in range(N)
])
print("2-Norm of the loss:", mean_loss)
assert mean_loss < 1e-5, "TEST FAILED"
print("TEST PASSED")

2-Norm of the loss: 7.986177550478365e-16
TEST PASSED


## 3. Square non-singular matrix

In [17]:
N = 5
A = np.random.uniform(-10, 10, size=(N, N))

print("Given matrix")
A.round(4)

Given matrix


array([[-8.5191, -2.8307, -7.6826,  7.2621,  2.466 ],
       [-3.382 , -8.7288, -3.7804, -3.4963,  4.5921],
       [ 2.7511,  7.7443, -0.5557, -7.6081,  4.2649],
       [ 5.2157,  1.2255,  5.4193, -0.1241,  0.4547],
       [-1.4492, -9.4916, -7.8422, -9.3714,  2.7282]])

In [18]:
eigenvalues = np.linalg.eig(A).eigenvalues
print("Eigenvalues:", eigenvalues)

Eigenvalues: [-0.4695158+10.50892633j -0.4695158-10.50892633j -8.2285539 +3.87064217j
 -8.2285539 -3.87064217j  2.1966181 +0.j        ]


Find eigenvectors

In [19]:
S = np.array([
    get_eigenvector_by_inviter(A, eigenvalue=l, max_iters=1500, noise_ratio=0.1)
    for l in eigenvalues
])

Restore original matrix from our decomposition

In [20]:
At = S.T @ np.diag(eigenvalues) @ inverse(S.T, eps=1e-15)
loss_matrix = At-A
print("Loss matrix")
print(loss_matrix.round(7))
print("2-Norm of loss:", np.linalg.norm(loss_matrix))

Loss matrix
[[ 2.0e-07+0.j -2.0e-07+0.j -0.0e+00+0.j  5.0e-07+0.j  2.0e-07-0.j]
 [ 0.0e+00-0.j -0.0e+00+0.j -0.0e+00-0.j  0.0e+00+0.j  0.0e+00+0.j]
 [-8.0e-07+0.j  6.0e-07-0.j  1.0e-07+0.j -1.5e-06-0.j -5.0e-07+0.j]
 [-2.0e-07-0.j  1.0e-07-0.j  0.0e+00-0.j -3.0e-07-0.j -1.0e-07+0.j]
 [-0.0e+00+0.j  0.0e+00+0.j  0.0e+00-0.j -1.0e-07-0.j -0.0e+00+0.j]]
2-Norm of loss: 1.9763187182169543e-06


In [21]:
print("Found vectors * lambda")
np.array([eigenvalues[i] * S[i] for i in range(N)])

Found vectors * lambda


array([[ 2.97745322-0.43805368j,  0.10623124-2.54893054j,
        -5.57752929-3.41546535j, -2.50765207+1.39431616j,
         1.71623526-6.41407753j],
       [ 3.00580388+0.14920359j,  0.35127134+2.52684397j,
        -5.22258571+3.93685598j, -2.63030261-1.14627423j,
         2.32611123+6.21892761j],
       [-0.11688507+6.27544229j, -2.48679157+1.88297806j,
         3.41765978-3.56803619j, -0.79330879-2.21034782j,
         0.26535788-1.88937068j],
       [ 3.54943506-5.17651898j, -0.9308402 -2.97712533j,
         0.70999917+4.88949709j, -1.92951045+1.33864325j,
        -0.88127014+1.69218773j],
       [ 1.58377361+0.j        , -0.2448231 +0.j        ,
        -1.09793866+0.j        ,  0.94447069+0.j        ,
         0.39919882+0.j        ]])

In [22]:
print("Found vectors after applying A")
np.array([A @ S[i] for i in range(N)])

Found vectors after applying A


array([[ 2.97745322-0.43805368j,  0.10623124-2.54893054j,
        -5.57752929-3.41546535j, -2.50765207+1.39431616j,
         1.71623526-6.41407753j],
       [ 3.00580388+0.14920359j,  0.35127134+2.52684397j,
        -5.22258571+3.93685598j, -2.63030261-1.14627423j,
         2.32611123+6.21892761j],
       [-0.11688507+6.27544229j, -2.48679157+1.88297806j,
         3.41765978-3.56803619j, -0.79330879-2.21034782j,
         0.26535788-1.88937068j],
       [ 3.54943506-5.17651898j, -0.9308402 -2.97712533j,
         0.70999917+4.88949709j, -1.92951045+1.33864325j,
        -0.88127014+1.69218773j],
       [ 1.58377317+0.j        , -0.24482311+0.j        ,
        -1.09793725+0.j        ,  0.94447098+0.j        ,
         0.39919887+0.j        ]])

In [23]:
mean_loss = np.mean([
    np.linalg.norm(A @ S[i] - eigenvalues[i] * S[i]) 
    for i in range(N)
])
print("2-Norm of the loss:", mean_loss)
assert mean_loss < 1e-5, "TEST FAILED"
print("TEST PASSED")

2-Norm of the loss: 3.0171655243390456e-07
TEST PASSED
